- ckanext/recombinant/read_xls.py
> treat blank numeric fields as 0s

- ckanext/recombinant/write_xls.py
provide both a belt and suspenders for xlsx template
> hilight header when bad values are pasted

- ckanext/recombinant/controller.py
- ckanext/recombinant/write_excel.py
Allows users to download specific records from a recombinant datatype in an excel template
> Edit in template

- ckanext/recombinant/write_excel.py
Note: Since visually the first resource title is the same as the PD title, the code adds resource titles for all resources except the first one. This condition can be removed if needed.
> OPN-650: writing better code to iterate through template resources

- ckanext/recombinant/templates/recombinant/resource_edit.html
This is required for the placement of the ATI email notice.
> added a new notices block to resource edit.

- ckanext/recombinant/templates/recombinant/confirm_delete.html
- ckanext/recombinant/templates/recombinant/resource_edit.html
- ckanext/recombinant/templates/recombinant/snippets/api_access.html
- ckanext/recombinant/templates/recombinant/snippets/delete.html
- ckanext/recombinant/templates/recombinant/snippets/org_select.html
Template updates for new View routes;
> More CKAN 2.9 Compatibly 

- ckanext/recombinant/plugins.py
- ckanext/recombinant/views.py
fix(views): added blueprint rules to prevent core form;
- Added view methods to redirect from the base dataset and resource edit view.
> Prevent Manage/Edit PD Type Datasets and Resource

- ckanext/recombinant/templates/package/activity.html
- ckanext/recombinant/templates/recombinant/resource_edit.html
- ckanext/recombinant/templates/snippets/activities/changed_package.html
- ckanext/recombinant/templates/snippets/activities/new_package.html
- ckanext/recombinant/templates/snippets/activity_stream.html
feat(templates): activity stream;
- Limited output of activity stream as Recombinant does not work like normal datasets.
> Prevent Display of Details for PD Activity Streams

- ckanext/recombinant/logic.py
- ckanext/recombinant/views.py
fix(views): redirect for org id, and support for org id in logic;
- Added redirect for view method from org id to org name.
- Added support to logic methods for org id just in case.
> Some Support for Org IDs

- ckanext/recombinant/auth.py
- ckanext/recombinant/plugins.py
- ckanext/recombinant/views.py
feat(auth): prevent users from modifying recombinant objects;
- Prevent update, patch, and delete of recombinant packages and resources.
> Prevent User Modification of Recombinant Packages and Resources

- ckanext/recombinant/errors.py
- ckanext/recombinant/logic.py
feat(sql): added trigger strings to trigger definitions;
- Added `trigger_strings` to trigger definitions.
> Trigger Strings

- ckanext/recombinant/views.py
fix(dev): force xlsx download for edge;
- Force xlsx downloads for MS Edge.
> Force XLSX Downloads for MS Edge

- ckanext/recombinant/auth.py
- ckanext/recombinant/logic.py
- ckanext/recombinant/plugins.py
feat(logic): prevent ds table deletions;
- Prevent Datastore table deletions for Recombinant types.
> Prevent Datastore Table Deletion

- changes/128.bugfix
- ckanext/recombinant/i18n/ckanext-recombinant.pot
- ckanext/recombinant/i18n/fr/LC_MESSAGES/ckanext-recombinant.po
- ckanext/recombinant/views.py
- ckanext/recombinant/write_excel.py
fix(views): language switching;
- Fix language switching in Flask.
> Fix Flask Language Switching

- changes/129.changes
- ckanext/recombinant/write_excel.py
- ckanext/recombinant/write_excel_v2.py
feat(dev): excel case sensitivity;
- Use `FIND` instead of `SEARCH`.
> Excel Case Sensitivity for `_text` Fields

- changes/130.changes
- ckanext/recombinant/i18n/ckanext-recombinant.pot
- ckanext/recombinant/i18n/fr/LC_MESSAGES/ckanext-recombinant.po
- ckanext/recombinant/templates/recombinant/snippets/data_dictionary.html
- ckanext/recombinant/views.py
- ckanext/recombinant/write_excel.py
feat(dev): max chars in data dict;
- Added `Character Limit` to data dictionaries.
> Character Limit in Data Dictionaries

- .github/workflows/flake8.yml
- .github/workflows/pyright.yml
- .gitignore
- changes/134.changes
- ckanext/recombinant/auth.py
- ckanext/recombinant/cli.py
- ckanext/recombinant/datatypes.py
- ckanext/recombinant/errors.py
- ckanext/recombinant/helpers.py
- ckanext/recombinant/load.py
- ckanext/recombinant/logic.py
- ckanext/recombinant/plugins.py
- ckanext/recombinant/read_csv.py
- ckanext/recombinant/read_excel.py
- ckanext/recombinant/tables.py
- ckanext/recombinant/tests/__init__.py
- ckanext/recombinant/tests/test_canonicalize.py
- ckanext/recombinant/validators.py
- ckanext/recombinant/views.py
- ckanext/recombinant/write_excel.py
- package-lock.json
- package.json
- pyproject.toml
- setup.cfg
- setup.py
> CKAN Coding Standards

- changes/138.bugfix
- ckanext/recombinant/cli.py
- ckanext/recombinant/read_csv.py
fix(cli): load csv;
- Load csv default org extras fix.
> Fix Load CSV Command

- changes/142.changes
- ckanext/recombinant/templates/recombinant/resource_edit.html
As described in the VA scan, all _blank targets should have rel="noopener norefferer" even if they are https and/or on the same domain.
> NoOpener & NoReferrer for _blank Targets

- changes/143.changes
- ckanext/recombinant/assets/css/recombinant.css
- ckanext/recombinant/templates/recombinant/resource_edit.html
- ckanext/recombinant/templates/recombinant/snippets/delete.html
- ckanext/recombinant/templates/recombinant/snippets/xls_upload.html
- ckanext/recombinant/templates/snippets/sysadmin_only.html
Related to https://github.com/open-data/ckanext-canada/pull/1599
Just need to move all in-tag style attributes to stylesheets.
> Move In Tag Styles to Stylesheet
